### ISSUE TITLE
Too large error log file on linux environment

### ISSUE THREAD

**Issue by sntntn** [sntntn/FitPlusPlus#4]
too large **error log file** on Linux environment

An oversized error log file in a Linux environment that causes the operating system to crash because the log file takes up all of the operating system's memory.

**Comment by sntntn** [comment]
I suggest you(@NataMata ) to focus on adapting the "ConnectionStrings" block for the Linux platform while solving this problem.
You can find that block in commit c7d9409.

**Comment by NataMata** [comment]
An oversized log file was caused by the constant restarting of Docker. Docker could not start the MSSQL container, so after each failure, it wrote logs to the log file and retried the start every 25 to 45 seconds. After a detailed investigation, it was discovered that the issue was caused by the kernel version. The initial version was 6.8.0, and after downgrading to 6.1.70, the problem was resolved.

**Comment by NataMata** [comment]
> I suggest you(@NataMata ) to focus on adapting the "ConnectionStrings" block for the Linux platform while solving this problem. You can find that block in commit [c7d9409](https://github.com/sntntn/FitPlusPlus/commit/c7d9409fc3a51dd8017d2a03e109f9076ae48d44).

Connection string has been restored to its previous state [d232ead](https://github.com/sntntn/FitPlusPlus/commit/d232ead91804e447cbfb59b8ab37e22c29a365c5)
. Correct value for "server" field is "localhost". Related issue was sovled by connecting to database manually before migrations.
